### ISSUE TITLE
Dockerfile build fails because default credentials are not included

### ISSUE THREAD

**Issue by nightpool** [GoogleCloudPlatform/reCAPTCHA-PLD#2] opened 2024-09-16 22:29 UTC
```
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   RecaptchaContextTests.shouldLoadDefaultCredentials:55 » IO Your default credentials were not found. To set up Application Default Credentials for your environment, see https://cloud.google.com/docs/authentication/external/set-up-adc.
[INFO] 
[ERROR] Tests run: 18, Failures: 0, Errors: 1, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:54 min
[INFO] Finished at: 2024-09-16T22:25:09Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.1.2:test (default-test) on project pld-service: 
[ERROR] 
[ERROR] Please refer to /build/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
The command '/bin/sh -c mvn test' returned a non-zero code: 1
```

**Comment by rvilgalys** [comment] 2024-09-26 14:56
Hi @nightpool, thanks for opening this. I'm not able to reproduce the issue, but this test shouldn't be blocking the build.

It looks like the underlying client library isn't finding the ADC and it's possible it was passing in our development environments because of the way ADC "magically" inherits credentials from the environment (http://cloud/docs/authentication/application-default-credentials).

Can you provide a few more details when you have time -- 

1. What environment & docker version is this running in?
3. What command are you using to build & is it any different from the README?
4. Are you intending to run with Application Default Credentials or an API Key?
5. Does following the URL in the error message (https://cloud.google.com/docs/authentication/provide-credentials-adc) resolve the issue if you tried it?

A potential workaround is to define the `APPLICATION_DEFAULT_CREDENTIALS` env var in some way (possibly by following the above URL). Even if you're not going to use ADC, as long as the env var is defined it should pass the test.

Adding `--build-arg APPLICATION_DEFAULT_CREDENTIALS="anything"` to the docker build command would meet this criteria.

**Comment by rvilgalys** [comment] 2024-10-24 15:30
We should have a fix for this in https://github.com/GoogleCloudPlatform/reCAPTCHA-PLD/pull/13

Please reopen if that's not the case!

**Closed by rvilgalys** 2024-10-24 15:30 UTC
